version: '3.8'
services:
  db:
    container_name: 'nest-prisma-graphql-2-db'
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nest_prisma_graphql_2
      # - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '0.0.0.0:5438:5432'
