version: '3.8'
services:  
  db:
    container_name: 'postgres-db'
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '0.0.0.0:5433:5432'

 # api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: gql-nest-prisma
  #   platform: linux/arm64/v8 # M1Mac対応
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     - mydb
  #   ports:
  #     - '0.0.0.0:8080:80'